Rails:
  Enabled: true

AllCops:
  Exclude:
    - db/schema.rb
    - modules/**/*
    - Puppetfile
    - Vagrantfile
    - Dockerfile

Metrics/LineLength:
  Max: 160

Style/Documentation:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Metrics/AbcSize:
  Exclude:
    - db/**/*

Metrics/MethodLength:
  Exclude:
    - db/**/*